################################################
# 1. Container configuration.

name: 'drupal'
type: 'php:8.0'

################################################
# 2. Builds, enabled extensions, and deploys.

build:
    flavor: composer

dependencies:
    php:
        composer/composer: '^2'

runtime:
    extensions:
        - redis
        - sodium
        - apcu
        - blackfire

hooks:
    build: |
        set -e
        composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
    deploy: |
        set -e
        php ./drush/platformsh_generate_drush_yml.php
        if [ -n "$(drush status bootstrap)" ]; then
            drush -y cache-rebuild
            drush -y updatedb
            if [ -n "$(ls $(drush php:eval "echo realpath(Drupal\Core\Site\Settings::get('config_sync_directory'));")/*.yml 2>/dev/null)" ]; then
                drush -y config-import
            else
                echo "No config to import. Skipping."
            fi
        else
            echo "Drupal not installed. Skipping standard Drupal deploy steps"
        fi

################################################
# 3. Web configuration.

web:
    locations:
        '/':
            root: 'web'
            expires: 5m
            passthru: '/index.php'
            allow: false
            rules:
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false
        '/sites/default/files':
            allow: true
            expires: 5m
            passthru: '/index.php'
            root: 'web/sites/default/files'
            scripts: false
            rules:
                '^/sites/default/files/(css|js)':
                    expires: 2w

################################################
# 4. Services.

relationships:
    database: 'db:mysql'
    redis: 'cache:redis'

################################################
# 4. Data.

disk: 2048

mounts:
    '/web/sites/default/files':
        source: local
        source_path: 'files'
    '/tmp':
        source: local
        source_path: 'tmp'
    '/private':
        source: local
        source_path: 'private'
    '/.drush':
        source: local
        source_path: 'drush'
    '/drush-backups':
        source: local
        source_path: 'drush-backups'
    '/.console':
        source: local
        source_path: 'console'

################################################
# 4. Scheduled tasks.

crons:
    drupal:
        spec: '*/19 * * * *'
        commands:
            start: 'cd web ; drush core-cron'
